import { Chapter } from './types';

export const INITIAL_CHAPTERS: Chapter[] = [
  { id: '1.1', title: 'The Journey from Traditional BI to Modern Analytics', status: 'validated', fileName: '010_chapter1_journey_traditional_bi_to_modern_analytics.md' },
  { id: '1.2', title: 'Limitations of Native Power BI Visuals', status: 'validated', fileName: '020_chapter1_limitations_native_power_bi_visuals.md' },
  { id: '1.3', title: 'Introduction to Inforiver Analytics+', status: 'validated', fileName: '030_chapter1_introduction_to_inforiver_analytics_plus.md' },
  { id: '1.4', title: 'Where Analytics+ Fits in the Microsoft Fabric Ecosystem', status: 'validated', fileName: '040_chapter1_where_analytics_plus_fits_microsoft_fabric_ecosystem.md' },
  { id: '2.1', title: 'Product Architecture and Components', status: 'validated', fileName: '050_chapter2_product_architecture_components.md' },
  { id: '2.2', title: 'Installation and Licensing Options', status: 'validated', fileName: '060_chapter2_installation_licensing_options.md' },
  { id: '2.3', title: 'First Steps with Analytics+', status: 'validated', fileName: '070_chapter2_first_steps_with_analytics_plus.md' },
  { id: '2.4', title: 'Interface Overview and Navigation Principles', status: 'validated', fileName: '080_chapter2_interface_overview_navigation_principles.md' },
  { id: '2.5', title: 'Integration with Power BI Workflow', status: 'validated', fileName: '100_chapter2_integration_with_power_bi_workflow.md' },
  { id: '2.6', title: 'CASE STUDY: Merck\'s Transition', status: 'validated', fileName: '110_chapter2_case_study_merck_excel_forecasting_transition.md' },
  { id: '3.1', title: 'Introduction to the Analytics+ Visualization Framework', status: 'validated', fileName: '120_chapter3_introduction_to_visualization_framework.md' },
  { id: '3.2', title: 'The Analytics+ Chart Type Gallery', status: 'validated', fileName: '130_chapter3_chart_type_gallery.md' },
  { id: '3.3', title: 'IBCS Certification and Implementation', status: 'validated', fileName: '140_chapter3_ibcs_certification_implementation.md' },
  { id: '3.4', title: 'Small Multiples Capabilities', status: 'validated', fileName: '150_chapter3_small_multiples_capabilities.md' },
  { id: '3.5', title: 'Pivot Data Interface', status: 'validated', fileName: '160_chapter3_pivot_data_interface.md' },
  { id: '3.6', title: 'Annotations and Analytical Storytelling', status: 'validated', fileName: '170_chapter3_annotations_analytical_storytelling.md' },
  { id: '3.7', title: 'Direct Manipulation Interface', status: 'validated', fileName: '180_chapter3_direct_manipulation_interface.md' },
  { id: '4.1', title: 'In-Visual Calculations Without DAX', status: 'validated', fileName: '190_chapter4_in_visual_calculations_without_dax.md' },
  { id: '4.2', title: 'Visual Formula Engine', status: 'validated', fileName: '200_chapter4_visual_formula_engine.md' },
  { id: '4.3', title: 'Conditional Formatting and Business Rules', status: 'validated', fileName: '210_chapter4_conditional_formatting_and_business_rules.md' },
  { id: '4.4', title: 'Interactive What-If Analysis', status: 'validated', fileName: '220_chapter4_interactive_what_if_analysis.md' },
  { id: '4.5', title: 'Template-Driven Development', status: 'validated', fileName: '230_chapter4_template_driven_development.md' },
  { id: '4.6', title: 'Comparative Analysis: Analytics+ vs. DAX Approach', status: 'validated', fileName: '240_chapter4_comparative_analysis_analytics_vs_dax.md' },
  { id: '5.1', title: 'Handling Large Datasets', status: 'validated', fileName: '250_chapter5_handling_large_datasets.md' },
  { id: '5.2', title: 'Performance Benchmarks vs. Native Visuals', status: 'validated', fileName: '260_chapter5_performance_benchmarks_vs_native_visuals.md' },
  { id: '5.3', title: 'Optimization Techniques for Enterprise Scale', status: 'validated', fileName: '270_chapter5_optimization_techniques_for_enterprise_scale.md' },
  { id: '5.4', title: 'Memory Management and Resource Utilization', status: 'validated', fileName: '280_chapter5_memory_management_and_resource_utilization.md' },
  { id: '5.5', title: 'Caching and Refresh Strategies', status: 'validated', fileName: '290_chapter5_caching_and_refresh_strategies.md' },
  { id: '5.6', title: 'CASE STUDY: Ibex\'s Shift to Real-Time Data', status: 'validated', fileName: '300_chapter5_case_study_ibex_shift_to_real_time_data.md' },
  { id: '6.1', title: 'Statistical Analysis Features', status: 'validated', fileName: '310_chapter6_statistical_analysis_features.md' },
  { id: '6.2', title: 'Trends and Forecasting Models', status: 'validated', fileName: '320_chapter6_trends_and_forecasting_models.md' },
  { id: '6.3', title: 'Outlier Analysis and Anomaly Detection', status: 'validated', fileName: '330_chapter6_outlier_analysis_and_anomaly_detection.md' },
  { id: '6.4', title: 'Comparative Analysis Tools', status: 'validated', fileName: '340_chapter6_comparative_analysis_tools.md' },
  { id: '6.5', title: 'Decision Support Visualizations', status: 'validated', fileName: '350_chapter6_decision_support_visualizations.md' },
  { id: '6.6', title: 'Advanced Drill-Down Techniques', status: 'validated', fileName: '360_chapter6_advanced_drill_down_techniques.md' },
  { id: '7.1', title: 'Analytics+ Planning Core Concepts', status: 'validated', fileName: '370_chapter7_analytics_planning_core_concepts.md' },
  { id: '7.2', title: 'Data Input and Validation', status: 'validated', fileName: '380_chapter7_data_input_and_validation.md' },
  { id: '7.3', title: 'Approval Workflows and Governance', status: 'validated', fileName: '390_chapter7_approval_workflows_and_governance.md' },
  { id: '7.4', title: 'Version Control and Scenario Planning', status: 'validated', fileName: '400_chapter7_version_control_and_scenario_planning.md' },
  { id: '7.5', title: 'Integration with Business Processes', status: 'validated', fileName: '410_chapter7_integration_with_business_processes.md' },
  { id: '7.6', title: 'Security and Access Controls', status: 'validated', fileName: '420_chapter7_security_and_access_controls.md' },
  { id: '8.1', title: 'Project Planning and Resource Allocation', status: 'validated', fileName: '430_chapter8_project_planning_and_resource_allocation.md' },
  { id: '8.2', title: 'Development Environments and Deployment Pipeline', status: 'validated', fileName: '440_chapter8_development_environments_and_deployment_pipeline.md' },
  { id: '8.3', title: 'Migration from Other Tools', status: 'validated', fileName: '450_chapter8_migration_from_other_tools.md' },
  { id: '8.4', title: 'Embedding and Integration Options', status: 'validated', fileName: '460_chapter8_embedding_and_integration_options.md' },
  { id: '8.5', title: 'Governance Framework Development', status: 'validated', fileName: '470_chapter8_governance_framework_development.md' },
  { id: '8.6', title: 'Performance Tuning and Optimization', status: 'validated', fileName: '480_chapter8_performance_tuning_and_optimization.md' },
  { id: '9.1', title: 'Stakeholder Analysis and Communication Plans', status: 'validated', fileName: '490_chapter9_stakeholder_analysis_and_communication_plans.md' },
  { id: '9.2', title: 'Role-Based Training Approaches', status: 'validated', fileName: '500_chapter9_role_based_training_approaches.md' },
  { id: '9.3', title: 'Developing Internal Champions', status: 'validated', fileName: '510_chapter9_developing_internal_champions.md' },
  { id: '9.4', title: 'Measuring Adoption and Usage', status: 'validated', fileName: '520_chapter9_measuring_adoption_and_usage.md' },
  { id: '9.5', title: 'Common Challenges and Solutions', status: 'validated', fileName: '530_chapter9_common_challenges_and_solutions.md' },
  { id: '9.6', title: 'Continuous Improvement Strategies', status: 'validated', fileName: '540_chapter9_continuous_improvement_strategies.md' },
  { id: '10.1', title: 'Financial Services Use Cases', status: 'validated', fileName: '550_chapter10_financial_services_use_cases.md' },
  { id: '10.2', title: 'Healthcare and Life Sciences Applications', status: 'validated', fileName: '560_chapter10_healthcare_and_life_sciences_applications.md' },
  { id: '10.3', title: 'Manufacturing and Supply Chain Solutions', status: 'validated', fileName: '570_chapter10_manufacturing_and_supply_chain_solutions.md' },
  { id: '10.4', title: 'Retail and Consumer Goods Implementations', status: 'validated', fileName: '580_chapter10_retail_and_consumer_goods_implementations.md' },
  { id: '10.5', title: 'Public Sector and Education Scenarios', status: 'validated', fileName: '590_chapter10_public_sector_and_education_scenarios.md' },
  { id: '10.6', title: 'Cross-Industry Best Practices', status: 'validated', fileName: '600_chapter10_cross_industry_best_practices.md' },
  { id: '11.1', title: 'Microsoft Fabric Integration', status: 'validated', fileName: '610_chapter11_microsoft_fabric_integration.md' },
  { id: '11.2', title: 'Power Platform Connectivity', status: 'validated', fileName: '620_chapter11_power_platform_connectivity.md' },
  { id: '11.3', title: 'API and Programmatic Access', status: 'validated', fileName: '630_chapter11_api_and_programmatic_access.md' },
  { id: '11.4', title: 'Custom Development Possibilities', status: 'validated', fileName: '640_chapter11_custom_development_possibilities.md' },
  { id: '11.5', title: 'Third-Party Tool Integration', status: 'validated', fileName: '650_chapter11_third_party_tool_integration.md' },
  { id: '11.6', title: 'The InfoBridge Vision and Ecosystem', status: 'validated', fileName: '660_chapter11_the_infobridge_vision_and_ecosystem.md' },
  { id: '12.1', title: 'Upcoming Features and Enhancements', status: 'validated', fileName: '670_chapter12_upcoming_features_and_enhancements.md' },
  { id: '12.2', title: 'AI and Machine Learning Integration', status: 'validated', fileName: '680_chapter12_ai_and_machine_learning_integration.md' },
  { id: '12.3', title: 'Emerging BI Trends and Analytics+ Positioning', status: 'validated', fileName: '690_chapter12_emerging_bi_trends_and_analytics_positioning.md' },
  { id: '12.4', title: 'Community and User-Driven Innovation', status: 'validated', fileName: '700_chapter12_community_and_user_driven_innovation.md' },
  { id: '12.5', title: 'Long-Term Vision for Analytics+', status: 'validated', fileName: '710_chapter12_long_term_vision_for_analytics.md' },
  { id: '12.6', title: 'Staying Updated with Analytics+ Evolution', status: 'validated', fileName: '720_chapter12_staying_updated_with_analytics_evolution.md' },
  { id: 'A.1', title: 'Detailed Visualization Capabilities', status: 'validated', fileName: '730_appendixa_detailed_visualization_capabilities.md' },
  { id: 'A.2', title: 'Performance Specifications and Limits', status: 'validated', fileName: '740_appendixa_performance_specifications_and_limits.md' },
  { id: 'A.3', title: 'System Requirements', status: 'validated', fileName: '750_appendixa_system_requirements.md' },
  { id: 'A.4', title: 'Competitive Feature Comparison Matrix', status: 'validated', fileName: '760_appendixa_competitive_feature_comparison_matrix.md' },
  { id: 'A.5', title: 'Security and Compliance Information', status: 'validated', fileName: '770_appendixa_security_and_compliance_information.md' },
  { id: 'B.1', title: 'Merck Case Study: Full Implementation Details', status: 'validated', fileName: '780_appendixb_merck_case_study_full_implementation_details.md' },
  { id: 'B.2', title: 'Adapa Case Study: Governance Model and Outcomes', status: 'validated', fileName: '790_appendixb_adapa_case_study_governance_model_and_outcomes.md' },
  { id: 'B.3', title: 'Ibex Case Study: Technical Architecture and Results', status: 'validated', fileName: '800_appendixb_ibex_case_study_technical_architecture_and_results.md' },
  { id: 'B.4', title: 'Additional Customer Success Stories', status: 'validated', fileName: '810_appendixb_additional_customer_success_stories.md' },
  { id: 'C.1', title: 'Business Analysts Guide', status: 'validated', fileName: '820_appendixc_business_analysts_guide.md' },
  { id: 'C.2', title: 'Finance Professionals Guide', status: 'validated', fileName: '830_appendixc_finance_professionals_guide.md' },
  { id: 'C.3', title: 'Sales and Marketing Teams Guide', status: 'validated', fileName: '840_appendixc_sales_and_marketing_teams_guide.md' },
  { id: 'C.4', title: 'Operations Managers Guide', status: 'validated', fileName: '850_appendixc_operations_managers_guide.md' },
  { id: 'C.5', title: 'Executive Leadership Guide', status: 'validated', fileName: '860_appendixc_executive_leadership_guide.md' },
  { id: 'C.6', title: 'IT Professionals Guide', status: 'validated', fileName: '870_appendixc_it_professionals_guide.md' },
  { id: 'D.1', title: 'Common Implementation Challenges', status: 'validated', fileName: '880_appendixd_common_implementation_challenges.md' },
  { id: 'D.2', title: 'Performance Optimization Guide', status: 'validated', fileName: '890_appendixd_performance_optimization_guide.md' },
  { id: 'D.3', title: 'Error Messages and Resolutions', status: 'validated', fileName: '900_appendixd_error_messages_and_resolutions.md' },
  { id: 'D.4', title: 'User Experience Enhancements', status: 'validated', fileName: '910_appendixd_user_experience_enhancements.md' },
  { id: 'D.5', title: 'Support Resources and Community', status: 'validated', fileName: '920_appendixd_support_resources_and_community.md' },
  { id: 'E.1', title: 'Business Intelligence Terminology', status: 'validated', fileName: '930_appendixe_business_intelligence_terminology.md' },
  { id: 'E.2', title: 'Inforiver-Specific Concepts', status: 'validated', fileName: '940_appendixe_inforiver_specific_concepts.md' },
  { id: 'E.3', title: 'Visualization Terminology', status: 'validated', fileName: '950_appendixe_visualization_terminology.md' },
  { id: 'E.4', title: 'Power BI and Microsoft Fabric Terms', status: 'validated', fileName: '960_appendixe_power_bi_and_microsoft_fabric_terms.md' },
  { id: 'E.5', title: 'Analytics and Reporting Concepts', status: 'validated', fileName: '970_appendixe_analytics_and_reporting_concepts.md' },
  { id: 'Appendix F', title: 'Working with Analytics+', status: 'validated', fileName: '980_appendixf_working_with_analytics_plus.md' }
];

export const INFORIVER_DOCS_URL = "https://docs.inforiver.com/analytics+?fallback=true";